### ISSUE TITLE
Error in environment setup

### ISSUE THREAD

**Issue by LittletreeZou** [bowang-lab/Orthrus#15]
I tried to setup the environment following the instructions, but when I tried to use `transformers` it returned the following error:
```
Traceback (most recent call last):
  File "/lustre/scratch/shared-folders/bio_project/shuxian/gbft/mg/rna_202507/Orthrus/tmp.py", line 2, in <module>
    from transformers import AutoModel
  File "/home/shuxian.zou/miniforge3/envs/orthrus/lib/python3.10/site-packages/transformers/__init__.py", line 27, in <module>
    from . import dependency_versions_check
  File "/home/shuxian.zou/miniforge3/envs/orthrus/lib/python3.10/site-packages/transformers/dependency_versions_check.py", line 16, in <module>
    from .utils.versions import require_version, require_version_core
  File "/home/shuxian.zou/miniforge3/envs/orthrus/lib/python3.10/site-packages/transformers/utils/__init__.py", line 24, in <module>
    from .auto_docstring import (
  File "/home/shuxian.zou/miniforge3/envs/orthrus/lib/python3.10/site-packages/transformers/utils/auto_docstring.py", line 30, in <module>
    from .generic import ModelOutput
  File "/home/shuxian.zou/miniforge3/envs/orthrus/lib/python3.10/site-packages/transformers/utils/generic.py", line 55, in <module>
    from ..model_debugging_utils import model_addition_debugger_context
  File "/home/shuxian.zou/miniforge3/envs/orthrus/lib/python3.10/site-packages/transformers/model_debugging_utils.py", line 30, in <module>
    from safetensors.torch import save_file
  File "/home/shuxian.zou/miniforge3/envs/orthrus/lib/python3.10/site-packages/safetensors/torch.py", line 439, in <module>
    torch.uint64: 8,
  File "/home/shuxian.zou/miniforge3/envs/orthrus/lib/python3.10/site-packages/torch/__init__.py", line 1938, in __getattr__
    raise AttributeError(f"module '{__name__}' has no attribute '{name}'")
AttributeError: module 'torch' has no attribute 'uint64'
```

Nor can I set up the environment successfully following the instructions at https://huggingface.co/antichronology/orthrus-4-track.

**Comment by IanShi1996** [comment]
Hey there!

Looks like this is caused by recent versions of `safetensors` expecting torch to have the `uint64` dtype. A temporary workaround is to downgrade to `safetensors==0.5.3`, and we'll get around to upgrading the dependencies in the near future.

**Comment by LittletreeZou** [comment]
Thank you for your prompt response! It works with safetensors==0.5.3.
